#!/bin/bash

# Generate ClawHub Import Report
# Usage: ./generate_report.sh

source .env

OUTPUT_FILE="CLAWHUB_IMPORT_REPORT_$(date +%Y%m%d_%H%M%S).md"

cat > "$OUTPUT_FILE" <<'HEADER'
# ClawHub Skills Import Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

---

## Executive Summary

HEADER

# Get statistics
TOTAL=$(psql "$DATABASE_URL" -t -c "SELECT COUNT(*) FROM skills WHERE namespace_id = (SELECT id FROM namespaces WHERE name = 'clawhub') AND framework = 'openclaw';" | tr -d ' ')

FIRST_IMPORT=$(psql "$DATABASE_URL" -t -c "SELECT MIN(created_at) FROM skills WHERE namespace_id = (SELECT id FROM namespaces WHERE name = 'clawhub') AND framework = 'openclaw';" | tr -d ' ')

LAST_IMPORT=$(psql "$DATABASE_URL" -t -c "SELECT MAX(created_at) FROM skills WHERE namespace_id = (SELECT id FROM namespaces WHERE name = 'clawhub') AND framework = 'openclaw';" | tr -d ' ')

cat >> "$OUTPUT_FILE" <<EOF

- **Total OpenClaw Skills Imported:** $TOTAL
- **First Import:** $FIRST_IMPORT
- **Latest Import:** $LAST_IMPORT
- **Source:** ClawHub.ai (OpenClaw Official Registry)
- **Framework:** openclaw
- **Namespace:** clawhub

---

## Import Statistics by Category

EOF

# Get top categories
psql "$DATABASE_URL" -t <<'SQL' >> "$OUTPUT_FILE"
SELECT '- **' || SPLIT_PART(name, '-', 1) || '**: ' || COUNT(*) || ' skills'
FROM skills
WHERE namespace_id = (SELECT id FROM namespaces WHERE name = 'clawhub')
AND framework = 'openclaw'
GROUP BY SPLIT_PART(name, '-', 1)
ORDER BY COUNT(*) DESC
LIMIT 20;
SQL

cat >> "$OUTPUT_FILE" <<'EOF'

---

## Top 20 Recently Imported Skills

EOF

psql "$DATABASE_URL" -t <<'SQL' >> "$OUTPUT_FILE"
SELECT '### ' || ROW_NUMBER() OVER (ORDER BY created_at DESC) || '. ' || name || '

**Description:** ' || LEFT(description, 150) || '...

**Created:** ' || created_at || '

'
FROM skills
WHERE namespace_id = (SELECT id FROM namespaces WHERE name = 'clawhub')
AND framework = 'openclaw'
ORDER BY created_at DESC
LIMIT 20;
SQL

cat >> "$OUTPUT_FILE" <<'EOF'

---

## All Imported Skills (Alphabetical)

EOF

psql "$DATABASE_URL" -t <<'SQL' >> "$OUTPUT_FILE"
SELECT '- `' || name || '` - ' || LEFT(description, 100)
FROM skills
WHERE namespace_id = (SELECT id FROM namespaces WHERE name = 'clawhub')
AND framework = 'openclaw'
ORDER BY name;
SQL

cat >> "$OUTPUT_FILE" <<'EOF'

---

## API Access

### Search ClawHub Skills

```bash
curl "https://aithub.space/v1/skills?namespace=clawhub&framework=openclaw&limit=50"
```

### Get Specific Skill

```bash
curl "https://aithub.space/v1/skills/clawhub/SKILL_NAME"
```

### Get Skill Content

```bash
curl "https://aithub.space/v1/skills/clawhub/SKILL_NAME/content"
```

---

## Technical Details

### Import Process

1. **Source:** ClawHub.ai API (`https://clawhub.ai/api/v1/`)
2. **Method:** Download ZIP packages, extract SKILL.md
3. **Transformation:** Add required fields (version, framework, tags)
4. **Validation:** Format validation, privacy scanning
5. **Storage:** PostgreSQL with full-text search indexing

### SKILL.md Format Conversion

ClawHub skills don't include `version` and `framework` fields. During import:

- Added `version: 1.0.0`
- Added `framework: openclaw`
- Added `tags: [openclaw, imported]`

### Rate Limiting

- ClawHub API: 180 req/min (unauthenticated)
- Import script: ~3 req/sec with delays
- Concurrent imports: Max 5 parallel

---

## Next Steps

### Import More Skills

```bash
# Import with different search queries
source .env
export ADMIN_TOKEN=$(cat /tmp/clawhub_token.txt)
./scripts/import_clawhub_batch.sh
```

### Monitor Imports

```bash
./scripts/monitor_import.sh
```

### Build Go Importer (Faster)

```bash
cd scripts
go build -o import_clawhub import_clawhub.go
./import_clawhub
```

---

## Resources

- [ClawHub.ai](https://clawhub.ai)
- [OpenClaw GitHub](https://github.com/openclaw/clawhub)
- [ClawHub Skill Format](https://github.com/openclaw/clawhub/blob/main/docs/skill-format.md)
- [AitHub API Docs](https://aithub.space/docs)

---

**Report Generated by:** AitHub ClawHub Importer
**Documentation:** `/opt/skillhub/scripts/CLAWHUB_IMPORT.md`

EOF

echo "Report generated: $OUTPUT_FILE"
cat "$OUTPUT_FILE"
